version: '3.8'

services:
  springboot-blog-rest-api:
    build:
      context: ./backend/springboot-blog-rest-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mysql
      - rabbitmq
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: myblog_v2
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/springboot-blog-rest-api/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5673:5672"
      - "15673:15672"
    restart: always

  my-socketio-server:
    build:
      context: ./backend/my-socketio-server
      dockerfile: Dockerfile
    ports:
      - "9092:9092"
    restart: always

  aoblo:
    build:
      context: ./frontend/aoblo
      dockerfile: Dockerfile
    environment: 
      - REACT_APP_API_URL=http://13.210.185.51:8080/api
      - REACT_APP_SOCKETIO=http://13.210.185.51:9092/
    ports:
      - "3000:3000"
    restart: always

volumes:
  db_data:
